# Generated by Django 4.0.6 on 2022-08-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=150)),
                ('post_about', models.CharField(max_length=50)),
                ('post_content', models.TextField()),
                ('post_pubDate', models.DateTimeField()),
                ('post_authorName', models.CharField(max_length=50)),
            ],
        ),
    ]
