# Generated by Django 4.0.6 on 2022-08-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='dbemail',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='dbname',
        ),
        migrations.AddField(
            model_name='contact',
            name='dbcontant',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
