# Generated by Django 4.0.6 on 2022-08-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_rename_email_contact_dbemail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='dbcontant',
            new_name='contact_contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='dbemail',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='dbname',
            new_name='contact_name',
        ),
    ]
