# Generated by Django 4.0.6 on 2022-08-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_rename_dbcontant_contact_contact_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_name',
            new_name='name',
        ),
    ]
