# Generated by Django 4.0.6 on 2022-08-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_rename_contact_email_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_contact',
            new_name='comment',
        ),
    ]
