# Generated by Django 4.0.6 on 2022-08-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_contact_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='timeStamp',
        ),
    ]
