# Generated by Django 4.0.6 on 2022-08-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0010_alter_post_post_about_alter_post_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
    ]
